Repository matiasdelellis/facerecognition, pull requests merged in 2018-12, with the labels that each got.

#57 Various really small fixes
  Makefile
  appinfo/database.xml
  lib/BackgroundJob/Tasks/AddMissingImagesTask.php
  lib/Db/PersonMapper.php
  lib/Migration/AddDefaultFaceModel.php
  tests/integration/AddMissingImagesTaskTest.php
  tests/unit/LockUnlockTaskTest.php
Labels: enhancement

#56 Adding logic to recreate existing clusters
  lib/BackgroundJob/Tasks/CreateClustersTask.php
  lib/Db/FaceNew.php
  lib/Db/FaceNewMapper.php
  lib/Db/ImageMapper.php
  lib/Db/PersonMapper.php
Labels: bug

#61 Dynamical image scaling, closes #59
  lib/BackgroundJob/Tasks/CheckRequirementsTask.php
  lib/BackgroundJob/Tasks/ImageProcessingTask.php
  lib/Helper/MemoryLimits.php
  tests/unit/ResizeTest.php
Labels: enhancement

#69 Fixing #67 and lowering memory limits to 3/4
  lib/BackgroundJob/Tasks/CheckRequirementsTask.php
  lib/BackgroundJob/Tasks/CreateClustersTask.php
  lib/BackgroundJob/Tasks/ImageProcessingTask.php
  lib/Db/Face.php
  lib/Helper/MemoryLimits.php
  tests/unit/MemoryLimitsTest.php
Labels: bug

#76 Consider the is_procesed in view of the FileController
  js/admin.js
  js/files-plugin.js
  js/files-tabview.js
  l10n/es.js
  l10n/es.json
  lib/Controller/FileController.php
  lib/Db/Image.php
  lib/Db/ImageMapper.php
  translationfiles/es/facerecognition.po
  translationfiles/templates/facerecognition.pot
Labels: help wanted

#87 Ignore small images (parametarized), fixes #65
  lib/BackgroundJob/Tasks/ImageProcessingTask.php
Labels: enhancement

#88 Split full image scans to be per user, fixes #85
  lib/BackgroundJob/Tasks/AddMissingImagesTask.php
  lib/Migration/RemoveFullImageScanDoneFlag.php
  lib/Watcher.php
  tests/integration/AddMissingImagesTaskTest.php
Labels: enhancement
